extends Node

const ICON_ATK = "res://Resources/Images/icon_atk.webp"
const ICON_DEF = "res://Resources/Images/icon_def.webp"
const ICON_LEVEL = "res://Resources/Images/icon_level.webp"

# Monster Attribute (DARK, LIGHT, etc.)
enum Attribute {
	DARK,
	LIGHT,
	WATER,
	FIRE,
	EARTH,
	WIND,
	SPELL,
	TRAP,
	NONE
}

enum Rarity {
	Common,
	Rare,
	Super_Rare,
	Ultra_Rare,
	Rush_Rare,
	Secret_Rare,
	Over_Rush_Rare,
	Gold_Rare,
	Promo,
	NONE
}

# Monster Types (Warrior, Spellcaster, Dragon, etc.)
enum MonsterType {
	Aqua,
	Beast,
	Beast_Warrior,
	Cyberse,
	Dinosaur,
	Divine_Beast,
	Dragon,
	Fairy,
	Fiend,
	Fish,
	Galaxy,
	High_Dragon,
	Insect,
	Machine,
	Omega_Psychic,
	Plant,
	Psychic,
	Pyro,
	Reptile,
	Rock,
	Sea_Serpent,
	Spellcaster,
	Thunder,
	Warrior,
	Winged_Beast,
	Wyrm,
	Zombie,
	NONE
}

# Card Types (Monster, Spell, Trap)
enum CardType {
	Monster,
	Spell,
	Trap
}

# Monster ability types
enum MonsterAbility {
	Normal,
	Effect,
	Fusion,
	Maximum
}

# Spell/Trap property
enum SpellTrapProperty {
	Normal,
	Continuous,
	Equip,
	Field,
	NONE
}

# Rush Duel doesn't have heroes, but we can track card series/archetypes
enum Series {
	None,
	Sevens_Road,
	Dragias,
	Gakuto,
	Romin,
	Luke,
	Yuga,
	Maximum
}

# Not used extensively in Rush Duel but kept for compatibility
enum SubType {
	None
}

enum Artist {
	Adolfo_Navarro,
	Agri_Karuniawan,
	Agus_Setiawan,
	Akifa_Shahgeldleva,
	Aleksey_Peregudov,
	Alena_Marchenko,
	Alexander_Gering,
	Alexander_Mokhov,
	Alexander_Nikolaev,
	Alexander_Pachin,
	Alexander_Staronosov,
	Alexandra_Malygina,
	Alexey_Peregrudov,
	Alexis_Susani,
	Alief_Rusdiatama,
	Alifka_Hammam_Nugroho,
	Alsu_Nurieva,
	Aluísio_Cervelle,
	Ambang_Tegar_Prakoso,
	Amelia_Tan,
	Anastasia_Alexandrova,
	Anastasia_Balakchina,
	Anastasia_Chernaya,
	Anastasia_Pronina,
	Anastasiya_Grintsova,
	Andi_Cahyo_W,
	Andrew_Chou,
	Andrey_Savchuk,
	Andy_Aslamov,
	Angelina_Tyshchik,
	Anna_Kharitonova,
	Anna_Tanygina,
	Anthony_Avon,
	Anton_Bezrukov,
	AOJI_Maiko,
	Arghawana_Rim,
	Arif_Wijaya,
	Arkoii,
	Artur_Treffner,
	Asep_Ariyanto,
	Askapoj_T,
	Asur_Misoa,
	Athiwut_B,
	Audy_Ravindra,
	Ausonia,
	Bastien_Jez,
	Billy_Christian,
	bimawithpencil,
	Bramasta_Aji,
	Brian_Adriel,
	Brian_Madya_Narendra,
	BWusagi,
	Camille_Alquier,
	Carlos_Cruchaga,
	Carlos_Jose_Camus,
	CGlas,
	Chris_Cold,
	Cindy_Handoyo,
	Cristián_Huerta,
	Daken,
	Daniel_Correia,
	Daniel_Jiménez,
	Daniil_Goncharov,
	Daria_Cherkashina,
	Daria_Khlebnikova,
	David_Ogilvie,
	Dmitriy_Semyonov,
	Dmitry_Isakevitch,
	Dmitry_Solodovnikov,
	Dominik_Mayer,
	Edward_Chee,
	Eilene_Cherie,
	Ekaterina_Revazashvili,
	Elena_Bakulina,
	Elena_Danilova,
	Elena_Perelygina,
	Eleonor_Piteira,
	Elina_Akhiamova,
	Elizaveta_Alipatova,
	Elizaveta_Zaichikova,
	Emanuel_Dias,
	Emilis_Emka,
	Enmoire,
	Eric_Klug,
	Erick_Efata,
	Eryk_Szczygieł,
	Esty_Swandana,
	Faizal_Fikri,
	Fajareka_Setiawan,
	Federico_Musetti,
	Fedor_Barkhatov,
	Felicia_Liang,
	Firaz_M_Rasyid,
	Flora_Silve,
	Galih_M,
	Gorshkov_Stanislav,
	Grant_Griffin,
	Grégory_Nunkovics,
	Grigoriy_Parshakov,
	Hatori_Kyoka,
	Hendry_Iwanaga,
	Henrique_Lindner,
	Henry_Leung,
	Hilary_Purnamasari,
	Hoàng_Lập,
	Iain_Miki,
	Igor_Heras,
	Immanuela_Crovius,
	Ina_Wong,
	Inkognit,
	Irene_Francisco,
	Irina_Kononenko,
	Irina_Plotnikova,
	Irina_Si,
	Ironical_Ghosty,
	Ismatulloh,
	Isuardi_Theriant,
	J_Sebastián_SC,
	Jackson_Tjota,
	Jason_Kiantoro,
	Jefrey_Yonathan,
	Jen_Santos,
	Jessada_Sutthi,
	Jessica_Nguyen,
	Jessketchin,
	Joseph_Qiu,
	Joshua_Raphael,
	Jsraphael,
	Junaidi_Lim,
	Kalashnikova_N,
	Kanadekana,
	Kate_Fox,
	Kelvin_Jauwri,
	Kevin_Sidharta,
	Kimberly_Pantoni,
	King_Fung_Ng,
	Ksenia_Belova,
	Kyxarie_Peralta,
	Le_Vuong,
	Leo_Avero,
	Leony_Tobing,
	Lius_Lasahido,
	Livia_Prima,
	Lizhe_Liang,
	M_Fakhrur_Rozzi,
	Mace_Tan,
	Madeline_Boni,
	Maerel_Hibadita,
	Marcellino_Tan,
	Marco_González,
	Marco_Wulfr,
	Marcus_Reyno,
	Maria_Mishina,
	Marina_Lunina,
	Mario_Wibisono,
	Mariusz_Gandzel,
	Mark_Poole,
	Masha_Mishina,
	Mateus_Manhanini,
	Mateusz_Wiśniewski,
	Max_Kostin,
	Maxim_Nikiforov,
	Michal_Makowski,
	Mihail_Spil_Haufter,
	Mike_Dalzell,
	Mikhail_Babkin,
	Milena_Vasyukova,
	Milivoj_Ćeran,
	MJ_Fetesio,
	Muhammad_Fajri,
	Murilo_Amgarten,
	Nailsen_Ivanderlie,
	Narendra_B_Adi,
	Nathaniel_Himawan,
	Nikita_Bondarev,
	Nikko_Wahyudi,
	Nikolai_Maslakov,
	Nikolay_Moskvin,
	Nuttapong_Thanawiwitaporn,
	Olga_Khariton,
	Olga_Krivolapova,
	Olga_Tereshenko,
	Oliver_Morit,
	Orson_CaptainSass,
	Othon_Nikolaidis,
	Oxana_Turlay,
	Pabel_Rtishchev_Klaher,
	Panji_Bagus_P,
	Pascal_Quidault,
	Patchanee_Treedet,
	Pavel_Chuvin,
	Pavel_Kondrashov,
	Petrinda_Wiyugo,
	Peyeyo,
	Phu_Thieu,
	Prisca_Ardiana,
	Rachel_Alderson,
	Ramza_Ardyputra,
	Raphael_Masalimov,
	Raphael_Pinna,
	Regina_Krivolapova,
	Revazashvili_E,
	Reza_Afshar,
	Reza_Aswadananta,
	Richard_Elrassi,
	Rio_Sabda,
	Riordan_Delmiro,
	Rodrigo_Rizo,
	romiy,
	Saad_Irfan,
	Sam_Yang,
	Samuel_Perin,
	Sandeep_Karunakaran,
	SanSan,
	Sariya_Asavametha,
	Satriasa,
	Sebastian_Giacobino,
	Sebastian_Szmyd,
	Septimius_Ferdian,
	Sergey_Averkin,
	Sergey_Gurskiy,
	Shen_Fei,
	Shiro_Yayoi,
	Silvia_Meiliani,
	Simon_Dominic,
	Simon_Wong,
	Soffani_Soffa,
	Sofia_Akimova,
	Sonia_Sandoval,
	Sooraj_Babu,
	soyameii,
	Stanislav_Sherbakov,
	Steve_Argyle,
	Stormy_Elia_Fanggidae,
	Surya_P,
	Surya_Prasteya,
	Tanapon_Wachirakul,
	Tatiana_Trubnikova,
	Thomas_Ressuge,
	Tian_Thongjomroon,
	Todor_Hristov,
	Tomasz_Jedruszek,
	Tommy_Suhartono,
	Trung_Tin_Shinji,
	Vadim_Kalabukh,
	Vathan_Suwannaworn,
	Vera_Rudichenko,
	Veto_Zomer,
	Victoria_Belyaeva,
	Viktoria_Belyaeva,
	Vito_Febrianno,
	Vito_Vivodka,
	Vlad_Tashkinov,
	Vlad_Varlamov,
	Vladimir_Shatunov,
	Widya_Wang,
	Wírawan_Pranoto,
	Wisnu_Tan,
	YDZ,
	Yen_Lee,
	Yeong_Hao_Han,
	Yiian_Kho,
	Yolanda_Felicia,
	Yugin_Maffioli,
	Yulia_Litvinova,
	Yulia_Tarushko,
	_Hiro_Suda
}

# Rush Duel has fewer keyword mechanics than other TCGs
# Keeping a simple enum for compatibility
enum Keyword {
	None
}

func get_card_resource_path(card_id: String) -> String:
	# Rush Duel set codes follow the format RD/XXNN where XX is the set type
	# For now, extract set from the card_id which contains set number like RD/KP01-JP001
	# The card resources will be organized by set code
	var sanitized_id = card_id.replace("/", "_").replace("-", "_")
	return "res://CardResources/%s.res" % [sanitized_id]
